apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: app1
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./clusters/my-cluster/app1
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
  targetNamespace: app1
  timeout: 1m0s
